### ISSUE TITLE
Bug on favorite contacts display in payment modal

### ISSUE THREAD

**Issue by stephansainleger** [Lokavaluto/monujo#133]
When we open the payment modal, there is a bug in the "Favorite" panel. Here is the expected behavior:
- if the search bar is empty, the favorite panel displays all the favorite contacts of the connected user
- if the search bar contains a string, the favorite panel displays the favorite contacts who match the search criteria
Could you please fix it asap ?

**Comment by SeddikKadi** [comment]
Beside all the others needed modifications, when the names are too long, do we allow the horizontal scroll or shrink the name and adding three dots ?

**Comment by seegwen** [comment]
@SeddikKadi my take on this is that there should not be horizontal scrollbars. You can have a look at how I fixed the names too long problem in the transactions list here, its pure CSS:
[https://github.com/Lokavaluto/monujo/commit/976ba6efdb73a5f7b80a99760b8dac3bf0bd9a91](chg: fix long text names overflowing the transactions list)
