### ISSUE TITLE
In recipient list of pay modals, what about the clock icon ?

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#147]
It seems this icon is related to history feature. For what I can recall, it was supposed to show last recipients. I think it was implemented through the list of last transactions. It seems broken and the icon doesn't make sense in the current implementation as far as I can tell.

Can we have the feature back or should we remove the icon ?

**Comment by MatSarr** [comment]
We should remove the icon for now. And in the future we'll see if we put it back with the last recipients feature
