### ISSUE TITLE
Basic error management in monujo is missing

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#148]
Lokapi will throw exceptions. In most calls to lokapi, no visible action for the end-user is taken to warn that the loading finished in an error, or resulted in a blocked / empty list because of an error. I suggest that we catch the errors and at least display something like "Uho, something went wrong, sorry. Please contact your administrator if this error doesn't go away."
It is nice that usable information is provided for debug in the javascript console also.

**Comment by seegwen** [comment]
@vaab can you describe a scenario to reproduce the errors you are describing ?
