### ISSUE TITLE
Payment modal, in the recipient list, improve the "(via xxx)" display

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#150]
By putting it in a different HTML placeholder, ideally on a second line to avoid having issues with wrapping.
And most importantly, avoid to display it if the current account is managing only one currency.

**Comment by MatSarr** [comment]
Is the '(via ...)' visible if only one main account?

If so, this issue is low prio because no lcc will have several main accounts for now
if not, this issue is high prio

**Comment by vaab** [comment]
It's complicated, but the short answer is : it is low prio

The longer answer is : it depends (1) if monujo is configured with both backends, and (2) if odoo server has both backends configured and ready. And by default it is even if this doesn't make sense and we could build a monujo for comchain only or cyclos only. By default, monujo has both capability.
