### ISSUE TITLE
Have a message explaining why monujo is empty when cyclos/comchain account not created yet

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/monujo#157]
So far:
![image](https://user-images.githubusercontent.com/46820746/159976204-4bc67133-d53f-42ea-96c6-b669be34ef88.png)

Would be great:
a message like: "Votre compte est en attente de validation"

**Comment by SeddikKadi** [comment]
@MatSarr  i couldn't reproduce the case where the message "Vous n'avez pas encore de compte"  is not displayed
can you help me about that ?

**Comment by MatSarr** [comment]
I've never seen the message "Vous n'avez pas encore de compte" , I tried on https://monujo.demo.lokavaluto.fr/#/ maybe it's note the last version of monujo. @stephansainleger ?

**Comment by SeddikKadi** [comment]
I think it’s been fixed since then.

**Comment by seegwen** [comment]
Yes, it has been fixed. The message "Vous n'avez pas encore de compte" (a pending PR will also add a link to directly create the wallet) and the message "Votre compte est en attente de validation" are already implemented.
