### ISSUE TITLE
Missing spinwheel in action async

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#187]
If we correctly have spinwheel displayed in various list and informational places, there are still some async call that do not trigger spinwheel and probably should : the action async : for instance when I click after giving my password to pay somebody on comchain we are using comchain's servers and this can take some time and this time is akward in monujo : no message, the password modal disappears... and nothing happens (sometimes more than 10sec).

I suggest to blackend the entire screen and put a spinwheel while waiting for answer.

I'd suggest also to do so in other action asyncs (validation of credit request and validation of account creations)

**Comment by SeddikKadi** [comment]
@vaab @seegwen @stephansainleger  Already resolved, we should close this PR
