### ISSUE TITLE
Reduce size credit box (and other box)

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/monujo#20]
from :
![image](https://user-images.githubusercontent.com/46820746/143605175-167304fe-3ce6-49b7-ae8e-908b1068cae6.png)

to something like that (and even smaller):

![image](https://user-images.githubusercontent.com/46820746/143605132-bfaad99b-b881-480e-9262-c90ecf2331f3.png)

**Comment by MatSarr** [comment]
I think it would be great that the web app looks like the odoo front end.
Odoo will be the portail for the user, and it will come back to odoo to credit his account.
For a better experience user, it would great that the shape of the boxes et text size be similar.
![image](https://user-images.githubusercontent.com/46820746/143608546-89e69df3-d35a-48ea-b31b-1dbe5c1623d6.png)

**Comment by seegwen** [comment]
Yikes !
I've been hacking for several hours on polishing quite a bit the UI ( #26 ) but I did not open this issue prior to it.
The thing is, your Odoo screenshot looks a lot like using the bootstrap framework.
But the webapp is using the bulma framework. With lots of customization...
It would be quite some work to switch to bootstrap. Not infeasable, but a looong time.

This is quite bugging. Your initial webapp devs should have considered this question from the start. But hey, can't think ahead of everything... ;-)

**Comment by njeudy** [comment]
Odoo visual aspect dépend on website thème .. think its not an issue, WE CAN not have same web app as odoo website ..

**Comment by MatSarr** [comment]
Sorry if there is a lack of understanding. I don't want the web app like Odoo. I just gave an exemple for the size of the text and the size of the windows

**Comment by MatSarr** [comment]
After the improvement for the UX, know the credit box is to big and the size of the text to small: 
![image](https://user-images.githubusercontent.com/46820746/144208966-7a682bf2-101b-476b-8948-2be7615a1f81.png)

**Comment by MatSarr** [comment]
and the connexion page is also to smal know:
![image](https://user-images.githubusercontent.com/46820746/144209125-d4e02a89-3bf5-4559-b70c-c22c258de18f.png)

It was better before.

The size of other text and  boxes is perfect!

**Comment by seegwen** [comment]
Ok, will look into it. @MatSarr or @vaab  can you assign me the issue pls ?

**Comment by seegwen** [comment]
Max width to take approx. from Mat's screenshot. Height should adapt to the content of the modal.

**Comment by seegwen** [comment]
@SeddikKadi Have you been told you can work on this issue ?
If so, be aware that there's a bug when visiting the site with a mobile phone and clicking on "recharger" or "payer": the bottom buttons dissapear randomly.

**Comment by SeddikKadi** [comment]
@seegwen Yes Valentin Lab told me so, i'll start working on it. thanks
