### ISSUE TITLE
Create 1 button "Create account" and a link "forget password?" in login page 

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/monujo#224]
at the right of "connexion" button create a similar size button "Create account"
and above add a link "forgotten password"

Or:
Beside  "connexion" button create 2 buttons "Create account" and "forgotten password"

![image](https://user-images.githubusercontent.com/46820746/168624078-5c313963-7a73-45d6-830b-612c0c320402.png)

**Comment by SeddikKadi** [comment]
![Screenshot from 2022-05-17 15-35-35](https://user-images.githubusercontent.com/44292235/168824157-48bbc452-aa99-4cac-a327-3a2b575f0612.png)
@MatSarr something like this ?

**Comment by SeddikKadi** [comment]
I just need the links for both "motde passe oublié" and "Créer un compte".
