### ISSUE TITLE
For comchain When no wallet created yet, add button "create account" in the place where the total amount is

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/monujo#227]
here:
![image](https://user-images.githubusercontent.com/46820746/168627829-8fe62420-cb0d-4347-8a71-32c567b209e6.png)

Baptiste_LaPive
10:15
l'idée ici c'est vraiment de guider les gens à aller sur le menu déroulant et cliquer sur "Créer mon portefeuille numérique" dans l'app. il n'est pas question de sortir de l'application mais simplement de fluidifier le parcours de ceux qui se sont déjà connecté dans l'appli et ne trouveraient pas qu'ils doivent cliquer sur leur nom, puis sur créer le portefeuille

**Comment by SeddikKadi** [comment]
perhaps by adding "Vous n'avez pas encore de compte (cliquez ici)link pour en créer un" ?

**Comment by MatSarr** [comment]
yes perfect thanks

**Comment by SeddikKadi** [comment]
ok
