### ISSUE TITLE
CGU and support buttons should be visible even if user is not connected

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/monujo#233]

**Comment by seegwen** [comment]
@MatSarr we have several choices here:
- Show the links in the top bar as long as the user is not connected (then we have an inconsistency with the `connected user` state, unless we also remove the links from the dropdown, or maybe we can live with the inconsistency ?)
- Show the links in a floating footer as long as the user is not connected (bizarre and also inconsistent) (why on earth did I think about that ?)
- Show the dropdown even if no user is connected (less desirable in my opinion, not very UX friendly)
- ... something I did not think of...
