### ISSUE TITLE
Upon transaction failed, no message is displayed to user

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#235]
Lokapi sends exceptions that are catched by monujo, but it only issues a message in the developper's console. This is not sufficient, and at least an error notification should be displayed to the user.

As a bonus, there are a few special exception type that are used and could be leveraged to translate some of the error cases:

https://github.com/Lokavaluto/lokapi-backend-comchain/blob/master/src/recipient.ts#L53-L55

And if it is another error, it should probably have a default text.

**Comment by vaab** [comment]
Note that vl_part4 on https://monujo.dev2.lokavaluto.fr was deactivated on the comchain level without odoo knowing about this. This allows to try to send money from or to it and reproduce this issue.

**Comment by seegwen** [comment]
At the time of me writing this, the errors are all catched by Monujo by default.
Just added a PR to catch the specific error you are talking about.

Thanks for the report.
