### ISSUE TITLE
Rework the wallet creation page styles so they are consistent with Monujo's design

### ISSUE THREAD

**Issue by seegwen** [Lokavaluto/monujo#240]
![Capture d’écran 2022-06-14 à 17 55 14](https://user-images.githubusercontent.com/2071961/173622451-20a02d7b-09ca-40d6-9530-e7116355fce0.png)

I'm thinking about the backend selector button.

Although a bit flashy, the alert message is OK to me, since the message is contains is really important for the user to read and take note of.

**Comment by SeddikKadi** [comment]
@seegwen i can try to make the cards elements a bit rounder (like the ones on the dashboard, change color of the backend button and check the font size and style ?
