### ISSUE TITLE
From dashboard, when page is refreshed, we come back to the login page

### ISSUE THREAD

**Issue by stephansainleger** [Lokavaluto/monujo#243]
Scenario (on dev2):
 - connected with account vl_part1@0k.io
 - on the dashboard
 - click on F5 key
 - I am sent to the login form

 UPDATE : same thing appends after a payment

**Comment by vaab** [comment]
This was only an issue in a PR that was under test. I don't think we should use github issues to give feedback on PR that are uder test, and in general for commits that are not on main.
Additionaly, this is not anymore an issue in the given PR, and was clearly identified as coming from the PR. So I'll close this.
