### ISSUE TITLE
Error Missing Gas not catch at payment time

### ISSUE THREAD

**Issue by stephansainleger** [Lokavaluto/monujo#245]
At payment step, when we have the error `Object { error: true, msg: "insufficient funds for gas * price + value", data: "" }`, nothing is displayed on the user screen and we don't know if the payment has been performed or not.

![image](https://user-images.githubusercontent.com/54352366/173794191-e4dc9df8-192d-4022-a68e-7af3b8ef535d.png)

We must have a message telling that:
- the transaction has been aborted
- the user can try again later, or contact an administrator

**Comment by seegwen** [comment]
@stephansainleger can you indicate the steps to reproduce the error please ?

**Comment by vaab** [comment]
This part was thoroughly checked, and the code as of now is clear cut. Any unknown exception will lead to the expected behavior. Additionnaly, we are asking for a confirmation by requesting the new transaction's information. I'll close this one as I think we have fixed all this.
