### ISSUE TITLE
Prevent monujo account deconnection when user switch between several app on his phone

### ISSUE THREAD

**Issue by stephansainleger** [Lokavaluto/monujo#252]
<p><b>Scenario:</b></p><ul><li><p>a user is connected on Monujo</p></li><li><p>he switch to another app (because SMS received for instance)</p></li><li><p>he comes back to Monujo =&gt; he is deconnected and has to fill its credentials again</p></li></ul><p><b>Expected behavior:</b> when he comes back after a short while, he is still connected and must not fill his credentials again.<br></p>

**Comment by seegwen** [comment]
Been able to reproduce the behaviour. But adding some useful info: the user is not actually disconnected from the app, he is simply navigated away from the `Dashboard` page, which is good news, since the fix will be quite easy.
