### ISSUE TITLE
we can go to the Dashboard even if we are not authenticated.

### ISSUE THREAD

**Issue by P-Lec** [Lokavaluto/monujo#282]
https://user-images.githubusercontent.com/94766388/188713301-57caf924-0010-4b14-9c44-34dd7e9a2755.MOV

https://user-images.githubusercontent.com/94766388/188713127-f4a23096-b445-4f89-8198-abd77a40d27a.MOV

**Comment by SeddikKadi** [comment]
@P-Lec i can not reproduce the bug, when i click on the logo i'm redirected to the GoGoCarto page. Can you give us more details about the senario you followed?

**Comment by P-Lec** [comment]
@SeddikKadi the scenario :

[Enregistrement de l’écran 2022-09-06 à 18.54.07.webm](https://user-images.githubusercontent.com/94766388/188696266-4ce765c2-0ffe-4583-abc6-b24f0ac90a56.webm)
