### ISSUE TITLE
Clean the code of the app 

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#33]
We are far from using the recommendation of vuejs... (cf: https://v3.vuejs.org/style-guide/#rule-categories ) in particular:

- [x] flat component directory (please read the rational from vuejs, I find it really pertinent)
- [x] Two words (at least) component name
   - still have `Modal` and `Dialog`, these are core elements re-used everywhere, could be legit for me.
- [x] Avoid abbreviations like `Accs` `Acc`, `Nav` except for `App` of course.
   - still have `Nav` which could seem legit to avoid full usage of `Naviguation` and in reference to `nav-bar` element. Could be ok for me.
- [x] Use descriptive word and avoid `Core`, `Modal` for instance...
   - still have `Modal`, but this is a generic Modal frame and seems legit to me.
- [x] (this is my wish) avoid positional naming of components (ie: RightCol), because in our new layout, the component might not be in a right col...
- [x] (this is my wish) removal of `Your` / `My` in component names (that were probably added in the first place to avoid naming collision because of using a directory hierarchy)
- [x] (this is my wish) useless comments (ie: `<!-- top of the file -->`), and french language comments
- [x] indentation ? (to do in a single commit, with only indentation concerns)
  - general syntax enforced via `prettier`.
- [ ] eslint pass ? (to do in a single commit, with only eslint pass)

Question, how can we enforce `eslint` pre-commit, or post-commit ?

Any other suggestions is welcomed. I have no style preference, it just need to be easily check-able consistent by everyone.

**Comment by vaab** [comment]
I noticed also that `views/` are only proxies, and I think this is not optimum. Indeed, I feel that the view should contain the master component that can't be re-used in other place. For each view, this means taking the only component they proxy and put it's code directly inside the view file and remove the component from the components.

**Comment by vaab** [comment]
I noticed also that the store has many useless `getters` (to my opinion). Indeed, for me `getters` on store, are comparable to `computed` on components : if we have a small computation to do that might be useful somewhere else we put it there, but if it is just a direct access to the state, we should directly use the state.

**Comment by vaab** [comment]
On the store, also, I'm not sure async mutations are to exist ! indeed, all these ideas of "committing" is also here to be sure what is done when to have a clean "history". Async mutations makes the code and state of the store really uncertain or at least more complicated to follow.

**Comment by vaab** [comment]
In the store, I do not really fancy naming like:
- `setBalCurr`
- `setThisWeekTransactions`

If we can stick to some naming rules:
- have a common and consistent vocabulary, for instance, no `Wallet` but `UserAccount`... we can talk about which to take for `Currency` (I have word `Symbol` in lokapi, and I'd like to be consistent).
- I feel lost with commits named `set*` ... I'd like them to be more precise `pullBackends` (or `fetchBackends`) would be better for me if there will be a httpRequest to feed info in the store

**Comment by vaab** [comment]
On the store: actions should do commits, if they are not doing commits, then they are probably getters. If they change the state, they should be mutations.

For instance `checkPasswordStrength` should be a `getter` I guess.

**Comment by vaab** [comment]
on the store, mutations are using 2 convention for naming mutation. Can we just stick to one ?

**Comment by seegwen** [comment]
I agree with almost all of your comments, thanks for all your suggestions, as they will really get us to a higher velocity.

> Question, how can we enforce eslint pre-commit, or post-commit ?

With a rejection in case of failure ?
We can start by using the 

> In the store, I do not really fancy naming like: [...]

Here is a suggestion. I like to use uppercase for their name so that I can identify them in the code at a glance, and use underscore_case.
Here is another one: Since mutations only deal with modifiying the state, I like to use `SET_FOO_BAR` to update a single value (or an entire array), `UPDATE_FOO_BAR` to update an array's single value or an object's single property. We can also have `RESTORE_FOO_BAR` to restore to default value, etc... IMHO, the prefix should reflect what it's doing to the store. That's how I view it.

> For instance checkPasswordStrength should be a getter I guess.

I don't completely agree with that. For me the best place is in an action.
But since the method you mention does not deal with the store state, it could be a direct call to $lokapi from the component since you've moved the `checkPasswordStrength` logic in the $lokapi service, and move `translatePwdFieldErrors` to a helper, or better yet, to a translation layer as to bypass entirely the store for the password strength logic.

Just my 2 cents, will probably think about some other points later...

**Comment by vaab** [comment]
About eslint enforcing, I know about, and could help putting in place tools that could:
- while you write, enforce style (``eslint --fix`` included in IDE)
- at commit time (commit hook) refuse the commit if it doesn't comply with style guide (I call this pre-commit)
- on github side, after receiving a set of commit, through hooks (I call this post-commit)

My feeling would go more on the IDE + pre-commit side. But I'm okay with anything that would move forward.

Vuex Store writing convention: 
- If we are free to change, I'd like to have reference (other projects that use this ? Style guides ? rationale about why ?)
- For your proposition, I'm not sure I like it much for these reasons:
   - I never saw it before (but my experience of vuex is much lighter than yours, so I guess you could probably convince me if you find other projects using that)
   - In a lot of language UPPERCASE_SNAKE_CASE_IS_USED_FOR_CONSTANTS ... (C, bash, python, java, ... ) 
   I would rather stick normal camelCase, or snake_case, although it seems camelCase is the most used in the javascript/typescript world. But I'm very open to being convinced...
   I heard your point for the visual impact, but aren't mutation called through `commit(..)` calls, alone in one line ? These are real big visual markers already, aren't they ? Maybe you are using some `map*` helpers and you don't have the word `commit` ?

For `checkPasswordStrength`, I kinda understand your point : it is calling a service in async. Getters should be small computation about the state only. So I agree.

**Comment by seegwen** [comment]
Vuex conventions:
I will go with whatever you prefer, since you seem to have strong opinions.
I'll adapt with joy. I don't have any preference.

**Comment by vaab** [comment]
Another interesting read concerning the store: https://medium.com/coding-blocks/writing-vuex-modules-in-neat-typescript-classes-9bf7b505e7b5

**Comment by vaab** [comment]
An issue I found problematic is the reset of the store forces us to duplicate some info: 
https://tkacz.pro/vue-vuex-reset-store-state-to-default-initial/
As a side node, please kindly note also, that this is the first example (for me in my little experience) that I cross that uses your suggestion of uppercase letters for mutations. I'm still curious (and open) to your suggestion, but I think I need more references and/or rationale. As the vast majority of other examples I found did not use this convention. This is not a majority contest, I'm still lacking of a few more examples to understand that it has some followers.

**Comment by vaab** [comment]
For uppercase in mutations: https://stackoverflow.com/questions/44571955/vuex-why-do-we-write-mutations-actions-and-getters-in-uppercase
This is an interesting reading, and this is my interpretation of this read:
- there are some people using it
- there are some people thinking this is a standard but misinterpret a very specific usage (computed property name), where
  it obviously stems from as the link with constants here is clear.
- there are some people bothered by the fact people mixes things up
Things get clearer at my level, and I'm 100% to use uppercase for mutation in computed property names if we use them (which we aren't right now, but we could). And I'd rather stick the the standard way as advertised in the vuex documentation itself and most example I saw.

**Comment by vaab** [comment]
Around the topic of mutation names and uppercasing : https://medium.com/@rijk/make-your-vuex-mutation-names-friendly-7e4b53597cd0 ...

**Comment by vaab** [comment]
Most of the original suggestions where properly applied. I'll close this and keep the `eslint` pass in a new issue.
