### ISSUE TITLE
transaction list doesn't need to be tabbed by `Passée, en cours, à venir`.

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#38]
Instead, these can be sections that are displayed (if transaction in this category exists), before the past transaction on the same list but with a discrete title (like "cette semaine").

```
UPCOMING
  - 20,00 LEM              mardi 30/12
PROCESSING
  - 10,00 LEM              jeudi 25/11
PAST
  -  5,00 LEM               ....
  -  3,00 LEM               ....
  - .... etc ... 
```

**Comment by seegwen** [comment]
Everyone agreed on removing this selector.
