### ISSUE TITLE
Remove Weclome, display the name of the logged in user in the top bar

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#39]
Could be placed temporarily next to the logo ?

**Comment by seegwen** [comment]
Not really much harder to float it on the right with the "disconnect" button on the far right. And when and only when we have a real "profile" page (with profile editing), we can move this disconnect and profile page in a dropdown.

**Comment by vaab** [comment]
I agree and share the same view.

**Comment by seegwen** [comment]
Resolved in PR #54
