### ISSUE TITLE
Change naming of buttons on the bottom of the screen

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#40]
We'd like one-word action verbe. "Payer", "Recevoir", "Recharger". Maybe add some icons ?

**Comment by vaab** [comment]
Found these unicode icons : ⮉ ⮋ ⬆

**Comment by MatSarr** [comment]
"Payer" --> ![image](https://user-images.githubusercontent.com/46820746/144198229-6afbf7a5-c10c-464b-b3ee-1753524cffbf.png) https://icons.getbootstrap.com/icons/box-arrow-up/

"Recevoir" --> ![image](https://user-images.githubusercontent.com/46820746/144197990-184c36e2-79bf-470b-863b-f1925a4a2ccd.png) https://icons.getbootstrap.com/icons/box-arrow-in-down/

"Recharger" --> ![image](https://user-images.githubusercontent.com/46820746/144197886-c32ea92b-7cb7-450a-9724-e4bbf820b2d0.png) https://icons.getbootstrap.com/icons/plus-square/

**Comment by vaab** [comment]
For the icon, as a suggestion: 

https://unicode-table.com/en/2B89/
https://unicode-table.com/en/2B8B/ 
https://unicode-table.com/en/2795/  (sign plus, qu'on pourrait négativer : mettre en blanc sur rond noir)
