### ISSUE TITLE
Upon loading, fonts seem to change at least 2 times

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#41]
Is it possible to change them only once if we allow lazy loading ? Is there anything we can make faster here ?

**Comment by seegwen** [comment]
I cannot seem to observe the behaviour that you're describing.
There might be a quirck in the css code. there should not be two custom fonts specifications.

Also, in my opinion, we should not rely on google cdn for the font, instead we should download it and host it ourselves.

**Comment by vaab** [comment]
I second your opinion on self hosting the font.

**Comment by MatSarr** [comment]
Same for me: can't reproduice and Ok to not rely on google
