### ISSUE TITLE
Change link for profile button

### ISSUE THREAD

**Issue by MatSarr** [Lokavaluto/monujo#44]
![image](https://user-images.githubusercontent.com/46820746/144403634-2835f59d-63e4-494e-ad00-61fdfa363ace.png)

link for profile button --> https://odoo12.dev.lokavaluto.fr/fr_FR/my/home

**Comment by seegwen** [comment]
@MatSarr Is this link still relevant ?
What are the URLs for the 4 staging servers (test, dev1, dev2, dev3) and for the demo and production instances.

I think we have to introduce a new env variable for this.
@vaab do you agree on my last proposal ?

**Comment by MatSarr** [comment]
Yes it's still relevant. But yes it's not a fixed linked for profile https://odoo12.dev.lokavaluto.fr/fr_FR/my/home it will be the url of the Odoo of the LCC . I guess the best way would be to have a field in monujo admin to add the link of the profile url after the installation. Same for the map

**Comment by vaab** [comment]
These are actually 2 different concerns. One for the Profile, that is solved in a PR, and one for a functional map. I'll split this in two because we can't introduce the map button without a real map to show.
