### ISSUE TITLE
Redesign paying modal to avoid necessity of scroll in most resolution

### ISSUE THREAD

**Issue by jcleonard2018** [Lokavaluto/monujo#50]
I have to scroll before seeing buttons.

Screen to pay, to credit. May be the text box can be smaller.

**Comment by jcleonard2018** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/39128793/145977255-07f58828-0e71-495e-af10-9b9adbe3248e.png">

**Comment by SeddikKadi** [comment]
change :
.modal-body {
  height: 100% !important;
  width: 100% !important;
}
to
.modal-body {
  height: auto !important;
  width: 100% !important;
}
