### ISSUE TITLE
searching paying recipients will not properly filter by active userAccounts

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#51]
When doing the search, we need to check if the current logged in user has at least one user account in the backends we are searching.

**Comment by seegwen** [comment]
@vaab
It looks like there is a choice needing to be done here and the answer is not clear to me:
Are you planning to put the filtering logic directly inside the lokApi or do I have the "GO" to implement it on the app side ?

**Comment by seegwen** [comment]
Thanks for the reply. Yes I do think it's doable as a post-list filter on monujo.
