### ISSUE TITLE
Add state indicators to lists (own accounts, transactions, pending accounts, pending credit requests)

### ISSUE THREAD

**Issue by seegwen** [Lokavaluto/monujo#73]
* A spinner indicating it's loading (we're using one already in views/Login.vue)
* Test if we have record, if not, add a message: "Il n'y a pas de xxx"

**Comment by seegwen** [comment]
I unassigned Nico from this issue since there was no news on this side and Seddik decided to work on this one.

**Comment by seegwen** [comment]
Only place where it's missing now is in the credit request page. Thanks for the work @SeddikKadi

**Comment by SeddikKadi** [comment]
@seegwen  @vaab  we should also add one in the search recipient modal.
