### ISSUE TITLE
Title of the web app does not reflect the actual name of the web app

### ISSUE THREAD

**Issue by seegwen** [Lokavaluto/monujo#75]

**Comment by seegwen** [comment]
Your fix is excellent, I commented on your PR, I would like it taken a little step further if it's OK with you.
See #81 for my comment.

**Comment by SeddikKadi** [comment]
Does this solution fit what you are suggesting?
Sorry for the multiple commits i'm also learning to use Github

**Comment by seegwen** [comment]
Sorry too, I am also learning to use git and github.
Can you overwrite your last three commits in your branch with one that contains all the changes ? Do you know how to do it ? 
In your CLI:
`git checkout set-title`
`git rebase -i HEAD~3`
This will open an interactive prompt, where you can rearrange your (here) last three commits.
I would `pick` the first, `fixup` the second and `fixup` the third. Don't worry, just follow the rebase and this last sentence will be clear to you.
