### ISSUE TITLE
"Credit" Modal : "Suivant" button creates a new quotation each times and nothing happens

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#8]
I expected button "Suivant" to go back, or to tell us what quotations are waiting to be paid.

Whatever is chosen, I didn't expect it to create as many quotation that I clicked on "Suivant". This might be a problem.

Could we at least:
- NOT create an additional quotation when clicking on "Suivant"  when we already have an url generated ?
- Maybe remove the button Suivant and change it to Done, or some text to explain that the account will only be credited
  when created order will be paid thanks to the given link ?

The suggestion of removing "Suivant", and having a "Done" button to close the modal avoids the user to click on the cross to close the modal, even if everything went as expected.

**Comment by vaab** [comment]
A link to see the current invoices and their status could be also given: https://odoo12.dev.lokavaluto.fr/my/invoices

**Comment by MatSarr** [comment]
I agree with @vaab

**Comment by stephansainleger** [comment]
I agree, this modification has already been asked to @AlexandreBrayer  :-) The idea is to replace the "Next" button by a "Done" button ("Terminer" in french), which close the credit modal and refresh the main page content.
