### ISSUE TITLE
Navbar does not support reload only on main screen

### ISSUE THREAD

**Issue by SeddikKadi** [Lokavaluto/monujo#82]
This happens on current main and is also happening on currently deployed dev3
we can notice this on pending-account and carto

**Comment by seegwen** [comment]
Right, reproduced, thanks.

It has to do with the autologin mechanism IIRC (which is in the file named components/Core.vue).
I think a good fit for this snippet would be the entrypoint component: "App.vue"

**Comment by seegwen** [comment]
I would add that it is an App-wide problem, not just related to the Nav component.
