### ISSUE TITLE
On pending-account page, replace empty list with a nice message

### ISSUE THREAD

**Issue by SeddikKadi** [Lokavaluto/monujo#83]
ex:   Aucun compte en attente de validation

please note that loading spinner might also be necessary to avoid displaying the "no message" while loading

**Comment by seegwen** [comment]
Hi @SeddikKadi, @vaab  thanks for reporting.
I will close this as it is a duplicate of #73.
Seddik, if you want to handle this, please get in touch with @njeudy who initially said he would take care of it.
:-)
