### ISSUE TITLE
Refresh action missing

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#9]
I'd like to be able to request a simple refresh of the default dashboard. 

It could simply be by a pull action towards the bottom as it is in several mobile app. Not sure if this is pertinent though for a web app.
A simple Refresh icon/text in the top bar could maybe also do the trick.

**Comment by MatSarr** [comment]
I agree. Most people don't have the F5 reflex, not even the reflex to use the refresh button of the browser.

It should be a text + an icon

**Comment by seegwen** [comment]
Agreed on floating it on the right of the title "VOS COMPTES"
