### ISSUE TITLE
Need a place to list all credit requests not already payed along with their link

### ISSUE THREAD

**Issue by vaab** [Lokavaluto/monujo#92]
If we don't click on the request right away, we loose the direct link to the right page. We can be tempted to create a lot of these unfinisehd and unpaid requests. It could be nice to list the undergoing credit requests somewhere in monujo and be able to click to get to the payment page again. An idea, is that they could be listed amongst transactions, as they are pending transactions that need to undergo a manual process (pay, and then being credited). This would avoid having a new screen to manage them.

**Comment by seegwen** [comment]
I second this issue. Can we get the status of a credit request via the lokapiLib yet ? From what I know, we can only get the pendingCreditRequests without distinctions and I guess that this method only returns the requests that have been fulfilled (paid) in odoo.
On the UI side, from what I see in [the templates/mockups of the web app](https://www.figma.com/proto/cPgeQkODWy74rNjsTONx7v/Loka-Web-App?page-id=301%3A236&node-id=305%3A7&viewport=-482%2C122%2C0.4156624674797058&scaling=scale-down-width) there should be a page presenting the details of a transaction for the user. This would be a good place to show the link to complete the request, along with a word in the transactions list showing what the state of the request is (could be in red when the transactions needs to be paid in odoo), inciting the user to click on the transactions, go into its details view, and click on the link to fulfill the request.

**Comment by vaab** [comment]
added in 165c042d6f2ee43fdc1add9b8e597b094755137f
