### ISSUE TITLE
The buttons "A un commercant / pro" and "a un particulier" generates a console error on the first click after loading modal

### ISSUE THREAD

**Issue by SeddikKadi** [Lokavaluto/monujo#94]

**Comment by seegwen** [comment]
@SeddikKadi You were posting this as we were conferencing on this very issue. And it seems there is work needed on the lokapi side.

**Comment by SeddikKadi** [comment]
@seegwen Understood, thanks for the quick response !

**Comment by seegwen** [comment]
No this is a regression bug, introduced by the credit modal flow which contained a refactoring that missed a hunk.

**Comment by seegwen** [comment]
Cowboy fix done in the concerned commit.
